deployment:
  tasks:
    # Paths
    - 'export DEPLOYPATH=/home/jox32g97phlr/public_html'
    - 'export REPOPATH=/home/jox32g97phlr/repositories/horizon_v_2'
    - 'export LOGFILE=/home/jox32g97phlr/deploy-$(date -u +%F_%H%M%S).log'

    # One bash run; capture all output to a timestamped log
    - >
      /bin/bash -lc '{
        echo "=== DEPLOY START $(date -u) ===";
        echo "[1/4] rsync from $REPOPATH to $DEPLOYPATH";
        rsync -a --delete
          --exclude=".git"
          --exclude="node_modules"
          --exclude=".env"
          --exclude="public/uploads/***"
          --exclude="public/premium-courses/***"
          --exclude="public/website-images/***"
          "$REPOPATH"/ "$DEPLOYPATH"/;

        echo "[2/4] artisan caches";
        cd "$DEPLOYPATH";
        php artisan optimize:clear || true;
        php artisan config:cache   || true;
        php artisan route:cache    || true;
        php artisan view:cache     || true;

        echo "[3/4] permissions";
        find "$DEPLOYPATH" -type f -exec chmod 644 {} \;;
        find "$DEPLOYPATH" -type d -exec chmod 755 {} \;;

        echo "[4/4] done";
        echo "=== DEPLOY END $(date -u) ===";
      } 2>&1 | tee "$LOGFILE"'
