deployment:
  tasks:
    - export DEPLOYPATH=/home/jox32g97phlr/public_html
    - export REPOPATH=/home/jox32g97phlr/repositories/horizon_v_2
    - /bin/bash -lc '
        set -e
        TS=$(date -u +%Y%m%dT%H%M%SZ)
        LOGDIR="$HOME/.cpanel/logs"; mkdir -p "$LOGDIR"
        LOG="$LOGDIR/deploy_$TS.log"

        {
          echo "== DEPLOY START $TS =="
          echo "[1/4] rsync from $REPOPATH to $DEPLOYPATH"
          rsync -av --delete \
            --exclude=".git" \
            --exclude="node_modules" \
            --exclude=".env" \
            --exclude="public/uploads/***" \
            --exclude="public/premium-courses/***" \
            --exclude="public/website-images/***" \
            "$REPOPATH"/ "$DEPLOYPATH"/

          echo "[2/4] artisan caches"
          cd "$DEPLOYPATH"
          /usr/local/bin/php artisan optimize:clear || true
          /usr/local/bin/php artisan config:cache   || true
          /usr/local/bin/php artisan route:cache    || true
          /usr/local/bin/php artisan view:cache     || true

          echo "[3/4] permissions"
          find "$DEPLOYPATH" -type f -exec chmod 644 {} \;
          find "$DEPLOYPATH" -type d -exec chmod 755 {} \;

          echo "[4/4] done"
        } | tee -a "$LOG"
      '
